services:
  app:
    build: .
    container_name: node_app_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    environment:
      - DB_HOST=db
      - DB_NAME=favorites
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: favorites
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  node_modules:
